export const nodes = [
  // Policies
  {
    id: "forest",
    type: "policy",
    x: 28,
    y: 28,
    labelJa: "植林・森林保全",
    labelEn: "Forest Planting",
    shortDescription: "流域保護のための植林",
    icon: "forest",
    fallbackIcon: "🌲",
  },
  {
    id: "levee",
    type: "policy",
    x: 45,
    y: 34,
    labelJa: "堤防・洪水対策",
    labelEn: "Levee Investment",
    shortDescription: "洪水防御のためのインフラ投資",
    icon: "levee",
    fallbackIcon: "🛡️",
  },
  {
    id: "paddyDam",
    type: "policy",
    x: 31,
    y: 51,
    labelJa: "田んぼダム",
    labelEn: "Paddy Field Dam",
    shortDescription: "農業用水保持インフラ",
    icon: "paddy",
    fallbackIcon: "💧",
  },
  {
    id: "relocation",
    type: "policy",
    x: 50,
    y: 56,
    labelJa: "移住・適応支援",
    labelEn: "Relocation Support",
    shortDescription: "居住者移転と強靭化",
    icon: "relocation",
    fallbackIcon: "🏘️",
  },
  {
    id: "preparedness",
    type: "policy",
    x: 27,
    y: 75,
    labelJa: "防災能力構築",
    labelEn: "Disaster Preparedness",
    shortDescription: "地域防災プログラム",
    icon: "preparedness",
    fallbackIcon: "🧰",
  },
  {
    id: "agriRnd",
    type: "policy",
    x: 43,
    y: 82,
    labelJa: "農業技術研究",
    labelEn: "Agricultural R&D",
    shortDescription: "耐熱農業・作物イノベーション",
    icon: "research",
    fallbackIcon: "🔬",
  },

  // Mechanisms
  {
    id: "forestWater",
    type: "mechanism",
    x: 42,
    y: 22,
    labelJa: "森林・水資源",
    labelEn: "Forest & Water",
    fallbackIcon: "🌿",
  },
  {
    id: "waterRetention",
    type: "mechanism",
    x: 50,
    y: 44,
    labelJa: "保水力",
    labelEn: "Water Retention",
    fallbackIcon: "💧",
  },
  {
    id: "floodDefense",
    type: "mechanism",
    x: 62,
    y: 30,
    labelJa: "防御インフラ",
    labelEn: "Flood Defense",
    fallbackIcon: "🏗️",
  },
  {
    id: "heatTolerance",
    type: "mechanism",
    x: 60,
    y: 74,
    labelJa: "高温耐性",
    labelEn: "Heat Tolerance",
    fallbackIcon: "🌡️",
  },
  {
    id: "residentResilience",
    type: "mechanism",
    x: 39,
    y: 66,
    labelJa: "住民レジリエンス",
    labelEn: "Resident Resilience",
    fallbackIcon: "🤝",
  },
  {
    id: "riskExposure",
    type: "mechanism",
    x: 64,
    y: 53,
    labelJa: "危険地域の住宅",
    labelEn: "Risk Exposure",
    fallbackIcon: "🏠",
  },
  {
    id: "policyCost",
    type: "mechanism",
    x: 58,
    y: 80,
    labelJa: "政策コスト",
    labelEn: "Policy Cost",
    fallbackIcon: "💰",
  },

  // Outcomes
  {
    id: "floodRisk",
    type: "outcome",
    x: 84,
    y: 16,
    labelJa: "洪水リスク",
    labelEn: "Flood Risk",
    icon: "flood",
    fallbackIcon: "🌊",
  },
  {
    id: "foodProduction",
    type: "outcome",
    x: 91,
    y: 38,
    labelJa: "食料生産",
    labelEn: "Food Production",
    icon: "crop",
    fallbackIcon: "🌾",
  },
  {
    id: "ecosystem",
    type: "outcome",
    x: 82,
    y: 63,
    labelJa: "生態系",
    labelEn: "Ecosystem",
    icon: "ecosystem",
    fallbackIcon: "🌳",
  },
  {
    id: "residentBurden",
    type: "outcome",
    x: 90,
    y: 84,
    labelJa: "住民負担",
    labelEn: "Resident Burden",
    icon: "burden",
    fallbackIcon: "👥",
  },
];

export const policyPathGroups = [
  {
    id: "forest_path",
    source: "forest",
    titleJa: "植林・森林保全",
    summaryJa: "森林を増やすことで流域の保水力を高め、洪水リスクを抑え、生態系の改善にもつながります。",
    noteJa: "植林の効果はすぐには現れず、長期的に効いてきます。",
    paths: [
      {
        chain: ["forest", "forestWater", "waterRetention", "floodRisk"],
        effect: "beneficial",
        strength: "medium",
        summaryJa: "森林が増えることで流域の保水力が高まり、洪水リスクを抑える効果があります。",
      },
      {
        chain: ["forest", "forestWater", "ecosystem"],
        effect: "beneficial",
        strength: "strong",
        summaryJa: "森林面積の増加は、生物多様性や生態系の改善につながります。",
      },
      {
        chain: ["forest", "policyCost", "residentBurden"],
        effect: "harmful",
        strength: "weak",
        summaryJa: "植林には一定の費用がかかるため、短期的には住民負担に影響する可能性があります。",
      },
    ],
  },
  {
    id: "levee_path",
    source: "levee",
    titleJa: "堤防・洪水対策",
    summaryJa: "堤防や洪水対策インフラを整備することで、豪雨時の洪水リスクを大きく下げることができます。",
    noteJa: "洪水対策として強力ですが、費用や環境面でのトレードオフがあります。",
    paths: [
      {
        chain: ["levee", "floodDefense", "floodRisk"],
        effect: "beneficial",
        strength: "strong",
        summaryJa: "堤防レベルが上がることで、豪雨時の洪水被害を抑える効果があります。",
      },
      {
        chain: ["levee", "policyCost", "residentBurden"],
        effect: "harmful",
        strength: "medium",
        summaryJa: "インフラ整備には大きな費用が必要なため、住民負担が増える可能性があります。",
      },
      {
        chain: ["levee", "ecosystem"],
        effect: "harmful",
        strength: "weak",
        summaryJa: "大規模な人工インフラは、生態系に負荷を与える可能性があります。",
      },
    ],
  },
  {
    id: "paddy_dam_path",
    source: "paddyDam",
    titleJa: "田んぼダム",
    summaryJa: "田んぼに一時的に水を貯めることで、水の流出を抑え、洪水リスクを下げる効果があります。",
    noteJa: "洪水対策として有効ですが、農業生産とのバランスが重要です。",
    paths: [
      {
        chain: ["paddyDam", "waterRetention", "floodRisk"],
        effect: "beneficial",
        strength: "medium",
        summaryJa: "田んぼに一時的に水を貯めることで、洪水リスクを下げる効果があります。",
      },
      {
        chain: ["paddyDam", "foodProduction"],
        effect: "harmful",
        strength: "weak",
        summaryJa: "水管理の制約により、農業収量に小さな負の影響が出る可能性があります。",
      },
      {
        chain: ["paddyDam", "policyCost", "residentBurden"],
        effect: "harmful",
        strength: "weak",
        summaryJa: "整備には費用がかかるため、住民負担に影響する可能性があります。",
      },
    ],
  },
  {
    id: "relocation_path",
    source: "relocation",
    titleJa: "移住・適応支援",
    summaryJa: "危険地域からの移住を支援することで、洪水時に被害を受ける住宅を減らします。",
    noteJa: "被害を減らす効果は大きい一方で、費用や住民生活への影響があります。",
    paths: [
      {
        chain: ["relocation", "riskExposure", "floodRisk"],
        effect: "beneficial",
        strength: "strong",
        summaryJa: "危険地域の住宅を減らすことで、洪水時の被害を抑える効果があります。",
      },
      {
        chain: ["relocation", "policyCost", "residentBurden"],
        effect: "harmful",
        strength: "medium",
        summaryJa: "移住支援には費用がかかるため、住民負担が増える可能性があります。",
      },
    ],
  },
  {
    id: "preparedness_path",
    source: "preparedness",
    titleJa: "防災能力構築",
    summaryJa: "住民の防災能力を高めることで、洪水時の被害を軽減できます。",
    noteJa: "防災能力は時間とともに低下するため、継続的な取り組みが重要です。",
    paths: [
      {
        chain: ["preparedness", "residentResilience", "floodRisk"],
        effect: "beneficial",
        strength: "medium",
        summaryJa: "住民の防災能力が高まることで、洪水時の被害を軽減できます。",
      },
      {
        chain: ["preparedness", "policyCost", "residentBurden"],
        effect: "harmful",
        strength: "weak",
        summaryJa: "防災訓練や啓発活動には継続的な費用が必要です。",
      },
    ],
  },
  {
    id: "agri_rnd_path",
    source: "agriRnd",
    titleJa: "農業技術研究",
    summaryJa: "高温に強い作物技術を研究することで、将来の食料生産を安定させます。",
    noteJa: "効果は累積投資によって段階的に現れるため、長期的な政策です。",
    paths: [
      {
        chain: ["agriRnd", "heatTolerance", "foodProduction"],
        effect: "beneficial",
        strength: "strong",
        summaryJa: "高温に強い作物技術が進むことで、将来の食料生産を安定させます。",
      },
      {
        chain: ["agriRnd", "policyCost", "residentBurden"],
        effect: "harmful",
        strength: "medium",
        summaryJa: "研究開発には継続的な投資が必要なため、住民負担に影響する可能性があります。",
      },
    ],
  },
];

export const outcomeExplanations = [
  {
    id: "floodRisk_explanation",
    target: "floodRisk",
    summaryJa:
      "洪水リスクは、豪雨の強さだけでなく、森林の保水力、防御インフラ、住宅の配置、住民の備えによって変化します。",
    relatedNodes: [
      "forest",
      "levee",
      "paddyDam",
      "relocation",
      "preparedness",
      "forestWater",
      "floodDefense",
      "waterRetention",
      "riskExposure",
      "residentResilience",
    ],
  },
  {
    id: "foodProduction_explanation",
    target: "foodProduction",
    summaryJa: "食料生産は、高温への作物耐性、水資源、田んぼダムの導入状況などによって変化します。",
    relatedNodes: ["agriRnd", "paddyDam", "heatTolerance", "waterRetention"],
  },
  {
    id: "residentBurden_explanation",
    target: "residentBurden",
    summaryJa:
      "住民負担は、政策コストと洪水被害の両方から影響を受けます。被害を減らす政策でも、短期的には負担が増えることがあります。",
    relatedNodes: [
      "forest",
      "levee",
      "paddyDam",
      "relocation",
      "preparedness",
      "agriRnd",
      "policyCost",
      "floodRisk",
    ],
  },
  {
    id: "ecosystem_explanation",
    target: "ecosystem",
    summaryJa: "生態系は、森林面積、水資源、人間によるインフラ整備の影響を受けます。",
    relatedNodes: ["forest", "forestWater", "waterRetention", "levee"],
  },
];
