import React, { createContext, useContext, useState } from 'react'

const LanguageContext = createContext({ lang: 'ja', toggle: () => {} })

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('ja')
  const toggle = () => setLang(l => l === 'ja' ? 'en' : 'ja')
  return (
    <LanguageContext.Provider value={{ lang, toggle }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useTranslation() {
  const { lang, toggle } = useContext(LanguageContext)
  const t = key => T[lang]?.[key] ?? T.en?.[key] ?? key
  return { t, lang, toggle }
}

const T = {
  en: {
    'entry.subtitle': 'Choose adaptation policies from 2026 to 2100.',
    'entry.username': 'Username',
    'entry.username.ph': 'Your name',
    'entry.team': 'Team name (optional)',
    'entry.team.ph': 'Team name',
    'entry.mode.label': 'Region mode',
    'entry.upstream.name': 'Upstream',
    'entry.upstream.desc': 'Forest / Levee / Paddy dam',
    'entry.downstream.name': 'Downstream',
    'entry.downstream.desc': 'Relocation / Training / Agriculture R&D',
    'entry.team.name': 'Team',
    'entry.team.desc': 'All 6 policies',
    'entry.rcp.label': 'Climate scenario',
    'entry.start': 'Start Simulation',
    'rcp.1.9.desc': 'Strong mitigation',
    'rcp.2.6.desc': 'Moderate mitigation',
    'rcp.4.5.desc': 'Intermediate',
    'rcp.6.0.desc': 'High emissions',
    'rcp.8.5.desc': 'Very high emissions',
    'topbar.simple': 'Overview',
    'topbar.detail': 'Detail',
    'topbar.analysis': 'Analysis',
    'topbar.upstream': 'UPSTREAM',
    'topbar.downstream': 'DOWNSTREAM',
    'topbar.team': 'TEAM',
    'report.subtitle': 'Cycle {n} / 25-Year Report',
    'report.title': '25-Year Report',
    'report.flood': 'Flood Damage',
    'report.crop': 'Crop Productivity',
    'report.eco': 'Ecosystem Points',
    'report.cta': 'View Details',
    'analysis.cld.title': 'System Structure',
    'analysis.cld.sub': 'SYSTEM DYNAMICS',
    'analysis.scatter.title': 'Policy x Outcome',
    'analysis.scatter.sub': 'SCATTER PLOT',
    'analysis.scatter.x': 'X',
    'analysis.scatter.y': 'Y',
    'analysis.scatter.empty': 'Run a simulation cycle to see data',
    'basin.header': 'BASIN STATUS',
    'basin.flood.label': 'Flood Risk',
    'basin.food.label': 'Crop Productivity',
    'basin.burden.label': 'Policy Points',
    'basin.eco.label': 'Ecosystem',
    'status.low': 'Low',
    'status.medium': 'Medium',
    'status.high': 'High',
    'status.stable': 'Stable',
    'status.declining': 'Declining',
    'status.critical': 'Critical',
    'status.manageable': 'Manageable',
    'status.elevated': 'Elevated',
    'status.severe': 'Severe',
    'status.healthy': 'Healthy',
    'status.stressed': 'Stressed',
    'status.degraded': 'Degraded',
    'decision.title': 'Policy Selection',
    'decision.sub': 'POLICY DECISIONS',
    'decision.advance': 'Advance 25 Years',
    'decision.loading': 'Running...',
    'decision.expand': 'Expand',
    'decision.collapse': 'Collapse',
    'tier.weak': 'Weak',
    'tier.standard': 'Standard',
    'tier.strong': 'Strong',
    'goal.upstream.1': 'Control flood risk while maintaining ecosystem health',
    'goal.upstream.2': 'Balance forest expansion with flood protection',
    'goal.upstream.3': 'Secure long-term watershed resilience',
    'goal.downstream.1': 'Reduce resident exposure to flood risk',
    'goal.downstream.2': 'Build preparedness and protect agriculture',
    'goal.downstream.3': 'Sustain safety through 2100',
    'goal.team.1': 'Balance flood, agriculture, and ecosystem outcomes',
    'goal.team.2': 'Adapt across the whole basin',
    'goal.team.3': 'Secure basin-wide resilience through 2100',
    'detail.chart.title': 'Indicators Over Time',
    'detail.chart.sub': 'INDICATORS',
    'detail.llm.title': 'AI Evaluation',
    'detail.llm.sub': 'COMMENTARY',
    'detail.llm.badge': 'CONNECTED',
    'detail.chart.empty': 'Advance the simulation to view charts',
    'detail.llm.empty': 'AI commentary will appear after each cycle',
    'detail.llm.loading': 'Generating AI evaluation...',
    'detail.llm.error': 'AI evaluation could not be generated.',
    'detail.llm.policy': 'POLICY READ',
    'detail.llm.comment': 'EXPERT VIEW',
    'detail.sns.title': 'Resident Reactions',
    'detail.sns.sub': 'RESIDENT VOICES',
    'detail.sns.empty': 'Resident reactions will appear after each cycle',
    'detail.sns.loading': 'Generating resident reactions...',
    'detail.sns.error': 'Resident reactions could not be generated.',
    'detail.sns.detail': 'Details',
    'detail.sns.detail_loading': 'Interviewing...',
    'detail.sns.satisfaction_score': 'Resident satisfaction',
    'consequence.continue': 'Continue',
    'ending.headline': "{name}'s Results",
    'ending.stats.flood': 'Flood Damage in 2100',
    'ending.stats.yield': 'Final Crop Productivity (kg/ha)',
    'ending.stats.eco': 'Final Ecosystem Points',
    'ending.compare': 'Compare Results',
    'ending.restart': 'Play Again',
    'comparison.kicker': 'RESULT COMPARISON',
    'comparison.title': 'Compare Final Outcomes',
    'comparison.back': 'Back',
    'comparison.loading': 'Loading comparison data...',
    'comparison.error': 'Some comparison data could not be loaded.',
    'comparison.scenario': 'Scenario',
    'comparison.yourResult': 'Your result',
    'comparison.noGroups': 'No saved group score data yet.',
  },
  ja: {
    'entry.subtitle': '2026年から2100年までの気候適応政策を選んでください。',
    'entry.username': 'ユーザー名',
    'entry.username.ph': 'あなたの名前',
    'entry.team': 'チーム名（任意）',
    'entry.team.ph': 'チーム名',
    'entry.mode.label': '地域モード',
    'entry.upstream.name': '上流域',
    'entry.upstream.desc': '植林・堤防・田んぼダム',
    'entry.downstream.name': '下流域',
    'entry.downstream.desc': '住宅移転・防災訓練・農業R&D',
    'entry.team.name': 'チーム',
    'entry.team.desc': '6政策すべて',
    'entry.rcp.label': '気候シナリオ',
    'entry.start': 'シミュレーション開始',
    'rcp.1.9.desc': '強い緩和',
    'rcp.2.6.desc': '中程度の緩和',
    'rcp.4.5.desc': '中間',
    'rcp.6.0.desc': '高排出',
    'rcp.8.5.desc': '非常に高い排出',
    'topbar.simple': '概要',
    'topbar.detail': '詳細',
    'topbar.analysis': '分析',
    'topbar.upstream': '上流域',
    'topbar.downstream': '下流域',
    'topbar.team': 'チーム',
    'report.subtitle': '第{n}ターン / 25年間レポート',
    'report.title': '25年間レポート',
    'report.flood': '洪水被害スコア',
    'report.crop': '農作物生産スコア',
    'report.eco': '生態系スコア',
    'report.cta': '詳細を見る',
    'analysis.cld.title': 'システム構造',
    'analysis.cld.sub': 'SYSTEM DYNAMICS',
    'analysis.scatter.title': '政策と結果',
    'analysis.scatter.sub': 'SCATTER PLOT',
    'analysis.scatter.x': 'X軸',
    'analysis.scatter.y': 'Y軸',
    'analysis.scatter.empty': 'シミュレーション後に表示されます',
    'basin.header': 'BASIN STATUS',
    'basin.flood.label': '洪水リスク',
    'basin.food.label': '農作物生産',
    'basin.burden.label': '政策ポイント',
    'basin.eco.label': '生態系',
    'status.low': '低',
    'status.medium': '中',
    'status.high': '高',
    'status.stable': '安定',
    'status.declining': '低下',
    'status.critical': '危機',
    'status.manageable': '管理可能',
    'status.elevated': '注意',
    'status.severe': '深刻',
    'status.healthy': '良好',
    'status.stressed': '負荷あり',
    'status.degraded': '悪化',
    'decision.title': '政策選択',
    'decision.sub': 'POLICY DECISIONS',
    'decision.advance': '25年進める',
    'decision.loading': '実行中...',
    'decision.expand': '開く',
    'decision.collapse': '閉じる',
    'tier.weak': '弱',
    'tier.standard': '標準',
    'tier.strong': '強',
    'goal.upstream.1': '洪水リスクと生態系のバランスを取る',
    'goal.upstream.2': '森林回復と治水を両立する',
    'goal.upstream.3': '長期的な流域の強さを確保する',
    'goal.downstream.1': '洪水リスクにさらされる住宅を減らす',
    'goal.downstream.2': '防災力と農作物生産を守る',
    'goal.downstream.3': '2100年まで安全性を保つ',
    'goal.team.1': '洪水・農業・生態系の3指標をバランスさせる',
    'goal.team.2': '流域全体で適応する',
    'goal.team.3': '2100年に向けた流域の強さを確保する',
    'detail.chart.title': '指標の推移',
    'detail.chart.sub': 'INDICATORS',
    'detail.llm.title': 'AI評価',
    'detail.llm.sub': 'COMMENTARY',
    'detail.llm.badge': '接続済み',
    'detail.chart.empty': 'シミュレーション後にグラフが表示されます',
    'detail.llm.empty': 'ターン終了後にAI評価が表示されます',
    'detail.llm.loading': 'AI評価を生成中...',
    'detail.llm.error': 'AI評価を生成できませんでした。',
    'detail.llm.policy': '政策評価',
    'detail.llm.comment': '専門家コメント',
    'detail.sns.title': '住民の反応',
    'detail.sns.sub': 'RESIDENT VOICES',
    'detail.sns.empty': 'ターン終了後に住民の反応が表示されます',
    'detail.sns.loading': '住民の反応を生成中...',
    'detail.sns.error': '住民の反応を生成できませんでした。',
    'detail.sns.detail': '詳細',
    'detail.sns.detail_loading': '聞き取り中...',
    'detail.sns.satisfaction_score': '住民満足度',
    'consequence.continue': '続ける',
    'ending.headline': '{name}さんの結果',
    'ending.stats.flood': '2100年の洪水被害',
    'ending.stats.yield': '最終農作物生産性（kg/ha）',
    'ending.stats.eco': '最終生態系ポイント',
    'ending.compare': '結果を比較する',
    'ending.restart': 'もう一度プレイ',
    'comparison.kicker': 'RESULT COMPARISON',
    'comparison.title': '最終結果の比較',
    'comparison.back': '戻る',
    'comparison.loading': '比較データを読み込み中...',
    'comparison.error': '一部の比較データを読み込めませんでした。',
    'comparison.scenario': 'シナリオ',
    'comparison.yourResult': 'あなたの結果',
    'comparison.noGroups': '保存済みのスコアはまだありません。',
  },
}
