// 日本語と英語のテキスト定義
export const texts = {
  ja: {
    title: '気候変動適応策検討シミュレーション',
    cycle: 'サイクル',
    year: '年',
    cropYield: '収穫量',
    floodDamage: '洪水被害',
    ecosystemLevel: '生態系',
    municipalCost: '予算',
    temperature: '年平均気温',
    precipitation: '年降水量',
    availableWater: '利用可能な水量',
    unit: {
      tonHa: 'ton/ha',
      manYen: '万円',
      none: '-',
      celsius: '℃',
      mm: 'mm',
      frequency: '回/年'
    },
    mode: {
      group: '（１）グループモード',
      upstream: '（２）上流モード',
      downstream: '（３）下流モード',
      groupDesc: '全ての項目を操作可能',
      upstreamDesc: '植林・河川堤防・田んぼダムのみ',
      downstreamDesc: '田んぼダム・住宅移転・防災訓練のみ'
    },
    predictMode: {
      bestWorst: 'モード（１）：ベストケース・ワーストケース',
      monteCarlo: 'モード（２）：モンテカルロシミュレーション（10回）',
      none: 'モード（３）：予測結果を表示しない'
    },
    settings: {
      title: '設定',
      predictDataMode: '折れ線グラフの予測データ表示モード',
      languageMode: '言語設定',
      close: '閉じる'
    },
    dialog: {
      nameTitle: 'お名前とモードを入力してください',
      nameLabel: 'お名前',
      modeTitle: 'モードを選択してください',
      register: '登録',
      nameError: 'この名前は既に使用されています。別の名前を入力してください。'
    },
    sliders: {
      plantingTrees: '植林・森林保全',
      damLevee: '河川堤防',
      agriculturalRnD: '高温耐性品種',
      houseMigration: '住宅移転',
      paddyDam: '田んぼダム',
      capacityBuilding: '防災訓練・啓発'
    },
    budget: {
      title: '政策予算ポイント',
      description: '住宅移転の影響は次のターンから、洪水被害額の影響は直前の25年被害から反映して、使える政策ポイントを計算します。',
      period: '対象期間',
      appliedFloodDamage: '予算反映洪水被害額',
      cumulativeRelocation: '累計住宅移転ポイント',
      floodReduction: '洪水減少',
      relocationReduction: '移転減少',
      totalReduction: '合計減少',
      availablePoints: '使用可能ポイント',
      usedPoints: '配分済みポイント',
      remainingPoints: '残りポイント',
      currentSelection: '現在の配分'
    },
    evaluation: {
      title: '新聞一面',
      description: '各25年区切りの終了後に、その期間の結果をもとに 新聞一面 と 住民別満足度 を表示します。SNS世論はボタンを押した時だけ生成されます。',
      periodLabel: '対象期間',
      modelLabel: '使用モデル',
      generating: 'gemma2:2b で新聞一面を生成しています...',
      pending: 'この25年区切りが完了すると、ここに新聞一面が表示されます。',
      errorMessage: '新聞一面の生成に失敗しました。Ollama の起動状態を確認してください。',
      policyAssessmentLabel: '政策評価',
      expertCommentLabel: '専門コメント',
      stage2050: '2050年時点の新聞一面',
      stage2075: '2075年時点の新聞一面',
      stage2100: '2100年時点の新聞一面'
    },
    council: {
      title: '住民別満足度',
      generating: '住民別満足度を生成しています...',
      pending: 'この25年区切りが完了すると、ここに4人の納得度が表示されます。',
      errorMessage: '住民別満足度の生成に失敗しました。Ollama の起動状態を確認してください。',
      childFuture: '小学生',
      entrepreneur: '若手起業家',
      councilMember: '市議会議員',
      farmer: '農家'
    },
    sns: {
      title: 'SNS世論',
      generateButton: 'SNS生成',
      regenerateButton: '再生成',
      generating: 'SNS世論を生成しています...',
      pending: 'ボタンを押すと、この期間のSNS投稿が表示されます。',
      disabledMessage: 'この段階が完了すると、SNS生成ボタンが使えます。',
      errorMessage: 'SNS世論の生成に失敗しました。Ollama の起動状態を確認してください。'
    },
    chart: {
      measuredValue: '実測値',
      upperLimit: '上限値予測',
      lowerLimit: '下限値予測',
      monteCarlo: 'モンテカルロ',
      selectYAxis: '縦軸を選択',
      years: 'Years',
      weatherCondition: '年の気象条件と将来影響予測',
      averageTemp: '年平均気温',
      annualPrecip: '年降水量',
      heavyRainFreq: '大雨の頻度',
      residentBurden: '住民の負担',
      biodiversity: '生物多様性',
      frequency: '回/年', 
      hotDays: '真夏日日数',
    },
    buttons: {
      advanceYears: '25年進める',
      inputComplete: '回の入力完了',
      nextCycle: '次のサイクル (',
      startNext: ') を開始',
      cycleComplete: 'サイクル',
      completed: 'が完了しました！',
      viewResults: '結果を見る',
    },
    rcp: {
      scenario: 'RCPシナリオ'
    },
    scatter: {
      title: 'サイクルの比較',
      description: '各サイクルを比較',
      xAxis: 'X軸',
      yAxis: 'Y軸',
      plotAttribute: 'プロット属性',
      average: '平均値',
      year2050: '2050年',
      year2075: '2075年', 
      year2100: '2100年',
      allDisplay: '全て表示',
      markerSize: 'マーカーサイズと透明度（時点）:',
      small: '2050年',
      medium: '2075年',
      large: '2100年',
      cycleColor: 'サイクルの色:',
      inputHistory: '各サイクルの入力履歴',
      cycle: 'サイクル',
      inputCount: '入力回数',
      inputYear: '入力年',
      noCompletedCycles: '完了したサイクルがありません。サイクルが完了すると結果が表示されます。',
      historyFilter: 'フィルター',
      historySort: 'ソート',
      filterAll: 'すべて',
      filterCycle1: 'サイクル1',
      filterCycle2: 'サイクル2',
      filterCycle3: 'サイクル3',
      sortByCycle: 'サイクル順',
      sortByYear: '年順',
      sortByInput: '入力回数順',
      yearFilter: '年次選択',
      cycleFilter: 'サイクル選択',
      allYears: 'すべての年次',
      allCycles: 'すべてのサイクル',
      cycleDisplayControl: 'サイクル表示制御'
    }
  },
  en: {
    title: 'Climate Change Adaptation Strategy Simulation',
    cycle: 'Cycle',
    year: 'Year',
    cropYield: 'Crop Yield',
    floodDamage: 'Flood Damage',
    ecosystemLevel: 'Ecosystem Level',
    municipalCost: 'Municipal Cost',
    temperature: 'Average Temperature',
    precipitation: 'Annual Precipitation',
    availableWater: 'Available Water',
    unit: {
      tonHa: 'ton/ha',
      manYen: '10k yen',
      none: '-',
      celsius: '°C',
      mm: 'mm',
      frequency: 'times/year'
    },
    mode: {
      group: '(1) Group Mode',
      upstream: '(2) Upstream Mode',
      downstream: '(3) Downstream Mode',
      groupDesc: 'All items can be operated',
      upstreamDesc: 'Forest conservation, river levee, paddy dam only',
      downstreamDesc: 'Paddy dam, house migration, disaster training only'
    },
    predictMode: {
      bestWorst: 'Mode (1): Best Case - Worst Case',
      monteCarlo: 'Mode (2): Monte Carlo Simulation (10 times)',
      none: 'Mode (3): No prediction display'
    },
    settings: {
      title: 'Settings',
      predictDataMode: 'Line Chart Prediction Data Display Mode',
      languageMode: 'Language Settings',
      close: 'Close'
    },
    dialog: {
      nameTitle: 'Enter your name and select mode',
      nameLabel: 'Name',
      modeTitle: 'Please select a mode',
      register: 'Register',
      nameError: 'This name is already in use. Please enter a different name.'
    },
    sliders: {
      plantingTrees: 'Forest Conservation',
      damLevee: 'River Levee',
      agriculturalRnD: 'Heat-resistant Varieties',
      houseMigration: 'House Migration',
      paddyDam: 'Paddy Dam',
      capacityBuilding: 'Disaster Training'
    },
    budget: {
      title: 'Policy Budget Points',
      description: 'Available policy points are calculated using flood damage from the previous 25-year period and relocation impacts from the previous turn.',
      period: 'Period',
      appliedFloodDamage: 'Flood Damage Used',
      cumulativeRelocation: 'Cumulative Relocation Points',
      floodReduction: 'Flood Reduction',
      relocationReduction: 'Relocation Reduction',
      totalReduction: 'Total Reduction',
      availablePoints: 'Available Points',
      usedPoints: 'Allocated Points',
      remainingPoints: 'Remaining Points',
      currentSelection: 'Current Allocation'
    },
    evaluation: {
      title: 'Newspaper Front Page',
      description: 'After each 25-year segment, the app shows a newspaper front page and resident satisfaction scores. SNS reactions are generated only when the button is pressed.',
      periodLabel: 'Period',
      modelLabel: 'Model',
      generating: 'Generating the newspaper front page with gemma2:2b...',
      pending: 'The newspaper front page will appear here after this 25-year segment is completed.',
      errorMessage: 'Failed to generate the newspaper front page. Check whether Ollama is running.',
      policyAssessmentLabel: 'Policy Assessment',
      expertCommentLabel: 'Expert Comment',
      stage2050: '2050 Newspaper Front Page',
      stage2075: '2075 Newspaper Front Page',
      stage2100: '2100 Newspaper Front Page'
    },
    council: {
      title: 'Resident Satisfaction Scores',
      generating: 'Generating resident satisfaction scores...',
      pending: 'After this 25-year segment is completed, the four persona scores will appear here.',
      errorMessage: 'Failed to generate resident satisfaction scores. Check whether Ollama is running.',
      childFuture: 'Child',
      entrepreneur: 'Entrepreneur',
      councilMember: 'Council Member',
      farmer: 'Farmer'
    },
    sns: {
      title: 'SNS Reactions',
      generateButton: 'Generate SNS',
      regenerateButton: 'Regenerate',
      generating: 'Generating SNS reactions...',
      pending: 'Press the button to generate SNS-style reactions for this period.',
      disabledMessage: 'The SNS button becomes available after this stage is completed.',
      errorMessage: 'Failed to generate SNS reactions. Check whether Ollama is running.'
    },
    chart: {
      measuredValue: 'Measured Value',
      upperLimit: 'Upper Limit Prediction',
      lowerLimit: 'Lower Limit Prediction',
      monteCarlo: 'Monte Carlo',
      selectYAxis: 'Select Y-axis',
      years: 'Years',
      weatherCondition: 'Weather Conditions and Future Impact Predictions',
      averageTemp: 'Average Temperature',
      annualPrecip: 'Annual Precipitation',
      heavyRainFreq: 'Heavy Rain Frequency',
      residentBurden: 'Resident Burden',
      biodiversity: 'Biodiversity',
      frequency: 'times/year',
      hotDays: 'Tropical Days',
    },
    buttons: {
      advanceYears: '25 years advance',
      inputComplete: 'inputs completed',
      nextCycle: 'Next Cycle (',
      startNext: ') Start',
      cycleComplete: 'Cycle',
      completed: 'completed!',
      viewResults: 'View Results',
    },
    rcp: {
      scenario: 'RCP Scenario'
    },
    scatter: {
      title: 'Cycle Comparison',
      description: 'Compare cycles',
      xAxis: 'X-axis',
      yAxis: 'Y-axis',
      plotAttribute: 'Plot Attribute',
      average: 'Average',
      year2050: '2050',
      year2075: '2075',
      year2100: '2100',
      allDisplay: 'All',
      markerSize: 'Marker Size and Opacity (Time Point):',
      small: '2050',
      medium: '2075',
      large: '2100',
      cycleColor: 'Cycle Color:',
      inputHistory: 'Input History for Each Cycle',
      cycle: 'Cycle',
      inputCount: 'Input Count',
      inputYear: 'Input Year',
      noCompletedCycles: 'No completed cycles. Results will be displayed when cycles are completed.',
      historyFilter: 'Filter',
      historySort: 'Sort',
      filterAll: 'All',
      filterCycle1: 'Cycle 1',
      filterCycle2: 'Cycle 2',
      filterCycle3: 'Cycle 3',
      sortByCycle: 'By Cycle',
      sortByYear: 'By Year',
      sortByInput: 'By Input Count',
      yearFilter: 'Year Selection',
      cycleFilter: 'Cycle Selection',
      allYears: 'All Years',
      allCycles: 'All Cycles',
      cycleDisplayControl: 'Cycle Display Control'
    }
  }
}; 
